language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - composer self-update
  - composer install --prefer-dist
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
